import { useEffect, useState } from "react"
import { useParams } from "react-router-dom"

const API = "https://veterinary-practice-manager.onrender.com"

export default function Emergency() {
  const { petName } = useParams()
  const [data, setData] = useState(null)
  const [error, setError] = useState("")

  useEffect(() => {
    fetch(`${API}/emergency/${petName}`)
      .then(res => res.json())
      .then(json => {
        if (json.error) setError(json.error)
        else setData(json)
      })
      .catch(() => setError("Unable to retrieve record"))
  }, [petName])

  if (error) {
    return (
      <div className="container" style={{textAlign: 'center', marginTop: '50px'}}>
         <h2 style={{ color: "#ef4444" }}>⚠️ {error}</h2>
         <p>Please contact the veterinary clinic directly.</p>
      </div>
    )
  }

  if (!data) {
    return (
      <div className="container" style={{textAlign: 'center', marginTop: '50px'}}>
        <div className="status loading">Fetching secure data...</div>
      </div>
    )
  }

  return (
    <div className="container">
      <div className="card emergency-layout">
        <div style={{textAlign: 'center'}}>
            <span className="emergency-badge">🚑 Emergency Medical ID</span>
            <h1>{data.pet_name}</h1>
        </div>
        
        <div style={{marginTop: '30px'}}>
            <label>Most Recent Medical Note</label>
            <div className="emergency-note">
                {data.last_note}
            </div>
        </div>

        <div style={{marginTop: '40px', textAlign: 'center', color: '#6b7280', fontSize: '0.9rem'}}>
          <p>⚠️ This information is intended for emergency veterinary use.</p>
          <p>Generated by Vet Practice Manager</p>
        </div>
      </div>
    </div>
  )
}